force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Reminder_Description__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Description__c</fullName>
    <label>Reminder Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_User__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pop_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SchedulePopReminderTest.cls
@IsTest
public class SchedulePopReminderTest {

    @TestSetup
    static void setup() {
        Profile p = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User'
        ];
        
        User testUser = new User(
        	Alias='dtest',
            Email='dale@test.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_us',
            ProfileId = p.Id,
            TimeZoneSidKey='Australia/Sydney',
            UserName='dtest@test.org'
        );
        insert testUser;
    }

    @IsTest
    static void testSendNotification() {
        Pop_User__c pUser = getPopUser(1)[0];
        insert pUser;
        
        List<Pop_Reminder__c> reminders = getPopReminder(2, pUser);

		Test.startTest();
		SchedulePopReminder spr = new SchedulePopReminder();
        Datetime scheduleTime = Datetime.now().addMinutes(1);
        String schCronExp = scheduleTime.format('s m H d M \'?\' yyyy');
        String jobId = System.schedule('Testingnow', schCronExp, spr);
        Test.stopTest();
        
        CronTrigger ct = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime
            FROM CronTrigger
            WHERE Id = :jobId
        ];
        
        System.assertEquals(schCronExp, ct.CronExpression, 'Cron Expression should equal.');
        System.assertEquals(0, ct.TimesTriggered, 'The job should not have run yet.');
    }
    
    private static List<Pop_User__c> getPopUser(Integer numPUsers) {
		User testUser = [
            SELECT Id
            FROM User
            WHERE UserName = 'dtest@test.org'
        ];
        
        List<Pop_User__c> pUsers = new List<Pop_User__c>();
        for(Integer i=0; i<numPUsers; i++) {
            Pop_User__c pUser = new Pop_User__c();
            pUser.Email__c = 'dale'+i+'test@testing.com';
            pUser.Persona__c = testUser.Id;
            pUsers.add(pUser);
        }
        
        return pUsers;
    }
    
    private static List<Pop_Reminder__c> getPopReminder(Integer numReminders, Pop_User__c pUser) {
        List<Pop_Reminder__c> reminders = new List<Pop_Reminder__c>();
        for(Integer i = 0; i<numReminders; i++) {
            Pop_Reminder__c pReminder = new Pop_Reminder__c();
            pReminder.Due_Date__c = Datetime.now().addMinutes(2);
            pReminder.Severity__c = 'Low';
            pReminder.Reminder_Description__c = 'Test Reminder '+i;
            pReminder.Pop_User__c = pUser.Id;
            reminders.add(pReminder);
        }
        
        return reminders;
    }

}