force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MockPopReminderDAOService.cls
public virtual class MockPopReminderDAOService implements PopReminderDAO {
    
    public virtual Pop_User__c getPopReminderUser() {
        return null;
    }
    
    public virtual User getCurrentUser() {
        return null;
    }
    
    public virtual Pop_Reminder__c selectReminderById(String reordId) {
        return null;
    }
    
    public virtual List<Pop_Reminder__c> selectRemindersByUserId(String userId) {
        return null;
    }
}