force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Reminder_Description__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Description__c</fullName>
    <label>Reminder Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_User__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pop_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PopReminderTriggerHandlerTest.cls
@IsTest
public class PopReminderTriggerHandlerTest {

    @IsTest
    static void testInsert() {
        Pop_User__c pUser = new Pop_User__c();
        pUser.Email__c = 'dale@test.com';
        pUser.Persona__c = UserInfo.getUserId();
        insert pUser;
        
        Pop_Reminder__c newReminder = new Pop_Reminder__c();
        newReminder.Due_Date__c = Datetime.now().addMinutes(2);
        newReminder.Severity__c = 'Low';
        newReminder.Reminder_Description__c = 'Testing reminder';
        newReminder.Pop_User__c = pUser.Id;
        
        Test.startTest();
        insert newReminder;
        Test.stopTest();
        
        List<CronTrigger> cts = [
            SELECT Id
            FROM CronTrigger
            WHERE State = 'WAITING'
            AND CronJobDetail.JobType = '7'
        ];
        
        System.assert(cts.size() > 0, 'A scheduled apex job should be triggered');
    }
    
    @IsTest
    static void testDelete() {
        Pop_User__c pUser = new Pop_User__c();
        pUser.Email__c = 'dale@test.com';
        pUser.Persona__c = UserInfo.getUserId();
        insert pUser;
        
        Pop_Reminder__c newReminder = new Pop_Reminder__c();
        newReminder.Due_Date__c = Datetime.now().addMinutes(2);
        newReminder.Severity__c = 'Low';
        newReminder.Reminder_Description__c = 'Testing reminder';
        newReminder.Pop_User__c = pUser.Id;
        insert newReminder;
        
        List<CronTrigger> cts = [
            SELECT Id
            FROM CronTrigger
            WHERE State = 'WAITING'
            AND CronJobDetail.JobType = '7'
        ];
        
        System.assert(cts.size() > 0, 'Before delete, there should be scheduled apex jobs.');
        
        Test.startTest();
        delete newReminder;
        Test.stopTest();
        
        List<CronTrigger> ctsNew = [
            SELECT Id
            FROM CronTrigger
            WHERE State = 'WAITING'
            AND CronJobDetail.JobType = '7'
        ];
        
        System.assert(ctsNew.size() == 0, 'There should be no scheduled apex jobs.');
    }
}