force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Reminder_Description__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Description__c</fullName>
    <label>Reminder Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Counting Down</fullName>
            </value>
            <value>
                <fullName>Almost Due</fullName>
            </value>
            <value>
                <fullName>Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProcessPopReminder.cls
public class ProcessPopReminder implements Database.Batchable<sObject> {
	public final String query;
    
    public ProcessPopReminder(String query) {
        this.query = query;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Pop_Reminder__c> scope) {
        Map<String, String> emailsToSend = new Map<String, String>();
        String dateFormat = 'yyyy-MM-dd HH:mm:ss';
        String rowStyle = 'padding:5px;border:1px solid #000';
        for(Pop_Reminder__c pReminder: scope) {
            PopReminderUtil.updateStatus(pReminder);
            String currentDescription = emailsToSend.get(pReminder.Pop_User__r.Email__c);
            String emailBody = PopReminderUtil.processDescription(
                currentDescription, 
                '<td style="'+rowStyle+'">' + pReminder.Due_Date__c.format(dateFormat) + '</td>' + 
                '<td style="'+rowStyle+'">' + pReminder.Reminder_Description__c + '</td>' +
                '<td style="'+rowStyle+'"><b>' + pReminder.Status__c + '</b></td>' +
                '<td style="'+rowStyle+'"><b>' + pReminder.Severity__c + '</b></td>'
            );
            emailsToSend.put(pReminder.Pop_User__r.Email__c, emailBody);
        }
        
        for(String emailKey: emailsToSend.keySet()) {
            PopReminderUtil.sendEmail(
                emailKey, 
                'Reminder for action', 
                emailsToSend.get(emailKey)
            );
        }
        
        if(!scope.isEmpty()) {
        	update scope;    
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
}