force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Reminder_Description__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Description__c</fullName>
    <label>Reminder Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Counting Down</fullName>
            </value>
            <value>
                <fullName>Almost Due</fullName>
            </value>
            <value>
                <fullName>Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SchedulePopReminder.cls
// SchedulePopReminder sw = new SchedulePopReminder();
// run at 2022-4-15 4:50pm
// String sch = '0 33 21 29 4 ? 2022';
// System.schedule('Testing4', sch, sw);
global class SchedulePopReminder implements Schedulable {

    global void execute(SchedulableContext sc) {
        // Get list of reminders that are due today. Send notification and update status to Due
        List<Pop_Reminder__c> reminders = [
            SELECT Id, Status__c, Due_Date__c, Reminder_Description__c, Pop_User__r.Email__c
            FROM Pop_Reminder__c
            WHERE Due_Date__c <= :Datetime.now()
        ];
        for(Pop_Reminder__c pReminder: reminders) {
            pReminder.Status__c = 'Due';
            PopReminderUtil.sendEmail(pReminder.Pop_User__r.Email__c, 'Reminder for action', pReminder.Reminder_Description__c);
        }
        update reminders;
        
        // Get list of reminders that are due tmr. Send notification and update status to Almost Due

        // Get list of reminders that are due the day after. Send notification and update status to Counting Down
        
    }
}