force-app/main/default/objects/Pop_Reminder__c/Pop_Reminder__c.object-meta.xml
<CustomObject>
    <label>Pop Reminder</label>
    <nameField>
        <label>Pop Reminder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Reminders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_Reminder__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Pop_User__c.field-meta.xml
<CustomField>
    <fullName>Pop_User__c</fullName>
    <label>Pop User</label>
    <referenceTo>Pop_User__c</referenceTo>
    <relationshipLabel>Pop Reminders</relationshipLabel>
    <relationshipName>Pop_Reminders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Reminder_Description__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Description__c</fullName>
    <label>Reminder Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_Reminder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Counting Down</fullName>
            </value>
            <value>
                <fullName>Almost Due</fullName>
            </value>
            <value>
                <fullName>Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pop_User__c/Pop_User__c.object-meta.xml
<CustomObject>
    <label>Pop User</label>
    <nameField>
        <label>Pop User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pop Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pop_User__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Persona</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pop_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PopReminderController.cls
public class PopReminderController {

    @auraenabled
    public static User getUser() {
        User user = new User();
        try {
            user = [
                SELECT Id, Name, Email
                FROM User
                WHERE Id = :UserInfo.getUserId()
            ];
        } catch (Exception e) {
            throw new AuraHandledException('User not found. ');
        }
        
        return user;
    }
    
    @auraenabled
    public static Pop_User__c getPopUser() {
        Pop_User__c pUser = new Pop_User__c();
        try {
            pUser = [
                SELECT Id, Name, Email__c, Persona__r.Name
                FROM Pop_User__c
                WHERE Persona__c = :UserInfo.getUserId()
        	];
        } catch(Exception e) {
            throw new AuraHandledException('Pop User not found. Please register');
        }
        return pUser;
    }
    
    @auraenabled
    public static void createPopUser(String email) {
        Pop_User__c pUser = new Pop_User__c();
        pUser.Email__c = email;
        pUser.Persona__c = UserInfo.getUserId();
        insert pUser;
    }
    
    @auraenabled
    public static void createReminders(List<Pop_Reminder__c> reminders) {
        Pop_User__c pUser = getPopUser();
        if(!reminders.isEmpty()) {
            for(Pop_Reminder__c reminder: reminders) {
            	reminder.Pop_User__c = pUser.Id;
        	}
            insert reminders;
        }
    }
    
    @auraenabled
    public static void deleteReminder(String recordId) {
        Pop_Reminder__c pReminder = [
            SELECT Id, Name
            FROM Pop_Reminder__c
            WHERE Id = :recordId
        ];
        delete pReminder;
    }
    
    @auraenabled(cacheable=true)
    public static List<String> getPickList(String objectName, String fieldName) {
        List<String> values = new List<String>();
        List<Schema.DescribeSObjectResult> results = Schema.describeSObjects(new List<String> {objectName});
        
        for(Schema.DescribeSObjectResult res: results) {
            for(Schema.PicklistEntry entry: res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if(entry.isActive()) {
                    values.add(entry.getValue());
                }
            }
        }
        return values;
    }
    
    @auraenabled(cacheable=true)
    public static List<Pop_Reminder__c> getPopReminders(String userId) {
        Pop_User__c pUser = getPopUser();
        return [
            SELECT Id, Name, Reminder_Description__c, Due_Date__c, Severity__c, Status__c
            FROM Pop_Reminder__c
            WHERE Pop_User__c = :pUser.Id
            ORDER BY Due_Date__c DESC
        ];
    }
    
    private class AuraException extends Exception {}
}